### ISSUE TITLE
小米调用获取访问凭证方法时报错

### ISSUE THREAD

**Issue by wxjbb** [biuaxia/editStepForLexinAndXiaoMi#6]
`java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_251]
	at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_251]
	at cn.biuaxia.code.sport.components.xiaomi.service.impl.XiaomiStepServiceImpl.getAccessCode(XiaomiStepServiceImpl.java:89) ~[classes/:na]
	at cn.biuaxia.code.sport.components.xiaomi.service.impl.XiaomiStepServiceImpl.submitStep(XiaomiStepServiceImpl.java:224) ~[classes/:na]
	at cn.biuaxia.code.sport.components.xiaomi.controller.XiaomiStepController.step(XiaomiStepController.java:47) ~[classes/:na]`

**Comment by wxjbb** [comment]
![image](https://user-images.githubusercontent.com/39824657/99179280-07b6f180-2757-11eb-9cf4-f82a37f2b9d1.png)

**Comment by biuaxia** [comment]
> `java.lang.IndexOutOfBoundsException: Index: 1, Size: 0 at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_251] at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_251] at cn.biuaxia.code.sport.components.xiaomi.service.impl.XiaomiStepServiceImpl.getAccessCode(XiaomiStepServiceImpl.java:89) ~[classes/:na] at cn.biuaxia.code.sport.components.xiaomi.service.impl.XiaomiStepServiceImpl.submitStep(XiaomiStepServiceImpl.java:224) ~[classes/:na] at cn.biuaxia.code.sport.components.xiaomi.controller.XiaomiStepController.step(XiaomiStepController.java:47) ~[classes/:na]`

这里是使用正则匹配获取内容。

你可以把 `params` 的内容log出来看一下是什么。

如果实在无法解决，可以钉钉联系我 [biuaxia]。

**Comment by wxjbb** [comment]
![image](https://user-images.githubusercontent.com/39824657/99208910-c7aa4a00-27fc-11eb-9b68-0a4db0acdda7.png)
这是param的内容。
钉钉搜索biuaxia，搜不到用户

**Comment by biuaxia** [comment]
> ![image](https://user-images.githubusercontent.com/39824657/99208910-c7aa4a00-27fc-11eb-9b68-0a4db0acdda7.png)
> 这是param的内容。
> 钉钉搜索biuaxia，搜不到用户

抱歉，dingtalk搜索 dawnme。

**Comment by biuaxia** [comment]
> ![image](https://user-images.githubusercontent.com/39824657/99208910-c7aa4a00-27fc-11eb-9b68-0a4db0acdda7.png)
> 这是param的内容。
> 钉钉搜索biuaxia，搜不到用户

我刚刚测试了一下，小米运动是可以的。出现401一般是参数没对导致的。是否修改过参数的内容呢？

**Comment by wxjbb** [comment]
理论上没改过代码，刚刚重新拉了一遍代码下来，然后运行还是401
![image](https://user-images.githubusercontent.com/39824657/99244639-56d75200-283d-11eb-9847-17ca9326ee66.png)

**Comment by biuaxia** [comment]
原因找到了，小米设置的密码过于复杂导致。

建议碰到此问题的同学修改简单的密码。
